-- MySQL Script generated by MySQL Workbench
-- Fri Dec  5 08:26:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rapido&seguro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rapido&seguro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rapido&seguro` DEFAULT CHARACTER SET utf8 ;
USE `rapido&seguro` ;

-- -----------------------------------------------------
-- Table `rapido&seguro`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido&seguro`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido&seguro`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido&seguro`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `localidade` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(100) NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  CONSTRAINT `fk_id_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapido&seguro`.`clientes` (`id_cliente`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rapido&seguro`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido&seguro`.`telefones` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `telefone_cliente` VARCHAR(20) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_telefone`),
  INDEX `fk_telefones_Clientes1_idx` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `telefone_cliente_UNIQUE` (`telefone_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapido&seguro`.`clientes` (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido&seguro`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido&seguro`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` DATE NOT NULL,
  `tipo_entrega` VARCHAR(10) NOT NULL,
  `distancia` DECIMAL(10,2) NOT NULL,
  `peso_carga` DECIMAL(10,2) NOT NULL,
  `valor_base_km` DECIMAL(10,2) NOT NULL,
  `valor_base_kg` DECIMAL(10,2) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  CONSTRAINT `fk_pedidos_Clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapido&seguro`.`clientes` (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido&seguro`.`calculo_entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido&seguro`.`calculo_entregas` (
  `id_entrega` INT NOT NULL AUTO_INCREMENT,
  `valor_distancia` DECIMAL(10,2) NOT NULL,
  `valor_peso` DECIMAL(10,2) NOT NULL,
  `acrescimo` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NOT NULL,
  `taxa_extra` DECIMAL(10,2) NULL,
  `valor_final` DECIMAL(10,2) NOT NULL,
  `status_entrega` VARCHAR(20) NOT NULL,
  `id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_entrega`),
  CONSTRAINT `fk_calculo_entregas_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `rapido&seguro`.`pedidos` (`id_pedido`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- O valor da distância é obtido pelo produto da distância da entrega (em quilômetros) pelo valor cobrado por quilômetro.
-- O valor do peso é obtido pelo produto do peso da carga (em quilogramas) pelo valor cobrado por quilo.
-- O valor base da entrega é a soma entre o valor da distância e o valor do peso.
-- Caso o tipo de entrega seja "urgente", aplica-se um acréscimo de 20% sobre o valor base. Se o tipo de entrega for "normal", nenhum acréscimo é aplicado.
-- O valor final da entrega é o resultado da soma entre o valor base e o acréscimo (caso aplicável).
-- Caso o valor final seja superior a R$ 500,00, aplicar um desconto de 10% sobre o valor final.
-- Caso o peso da carga ultrapasse 50 kg, adicionar uma taxa fixa adicional de R$ 15,00 ao valor final.

DELIMITER $$

CREATE TRIGGER calcular_valores_pedido_insert
AFTER INSERT ON pedidos
FOR EACH ROW
BEGIN

    DECLARE pValorDistancia DECIMAL(10,2);
    DECLARE pValorPeso DECIMAL(10,2);
    DECLARE pAcrescimo DECIMAL(10,2);
    DECLARE pDesconto DECIMAL(10,2);
    DECLARE pTaxaExtra DECIMAL(10,2);
    DECLARE pValorFinal DECIMAL(10,2);

    -- Calcula valor da distância e do peso
    SET pValorDistancia = NEW.distancia * NEW.valor_base_km;
    SET pValorPeso = NEW.peso_carga * NEW.valor_base_kg;

    -- Calcula acréscimo se a entrega urgente
    IF NEW.tipo_entrega = 'urgente' THEN
        SET pAcrescimo = (pValorDistancia + pValorPeso) * 0.2;
    ELSE
        SET pAcrescimo = 0;
    END IF;

    -- Valor antes do desconto e da taxa
    SET pValorFinal = pValorDistancia + pValorPeso + pAcrescimo;

    -- Se valor final for maior 500 ele coloca um desconto de 10%
    IF pValorFinal > 500 THEN
        SET pDesconto = pValorFinal * 0.10;
        SET pValorFinal = pValorFinal - pDesconto;
    ELSE
        SET pDesconto = 0;
    END IF;

    -- Adiciona taxa extra se peso for maior que 50kg
    IF NEW.peso_carga > 50 THEN
        SET pTaxaExtra = 15;
        SET pValorFinal = pValorFinal + pTaxaExtra;
    ELSE
        SET pTaxaExtra = 0;
    END IF;

    INSERT INTO calculo_entregas (
        valor_distancia, valor_peso, acrescimo, desconto, taxa_extra, valor_final, status_entrega, id_pedido
    ) VALUES (
        pValorDistancia, pValorPeso, pAcrescimo, pDesconto, pTaxaExtra, pValorFinal, 'calculado', NEW.id_pedido
    );
END$$

DELIMITER ;

